name: Unused-Code Check

on:
  pull_request:
    branches: [ main ]

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run knip
        run: npm run knip
